import { db } from './index';
import { categories, sources, salesData, chargingStations } from './schema';

async function seed() {
  console.log('Seeding categories...');
  await db.insert(categories).values([
    { slug: 'new-car', nameZh: '新车发布', nameEn: 'New Car', sortOrder: 1 },
    { slug: 'sales', nameZh: '销量数据', nameEn: 'Sales', sortOrder: 2 },
    { slug: 'technology', nameZh: '技术发布', nameEn: 'Technology', sortOrder: 3 },
    { slug: 'charging', nameZh: '闪充桩', nameEn: 'Charging', sortOrder: 4 },
    { slug: 'overseas', nameZh: '海外市场', nameEn: 'Overseas', sortOrder: 5 },
  ]).onConflictDoNothing();

  console.log('Seeding sources...');
  await db.insert(sources).values([
    { name: 'BYD Official', rssUrl: 'https://www.byd.com/en/news/rss', categoryId: 1, isActive: true },
    { name: 'CnEVPost', rssUrl: 'https://cnevpost.com/feed/', categoryId: 2, isActive: true },
    { name: 'Electrek', rssUrl: 'https://electrek.co/feed/', categoryId: 1, isActive: true },
    { name: 'InsideEVs', rssUrl: 'https://insideevs.com/rss.xml', categoryId: 3, isActive: true },
    { name: 'CleanTechnica', rssUrl: 'https://cleantechnica.com/feed/', categoryId: 3, isActive: true },
    { name: 'BYD Global', rssUrl: 'https://www.byd.com/en/press/rss', categoryId: 5, isActive: true },
    { name: 'Green Car Reports', rssUrl: 'https://www.greencarreports.com/rss.xml', categoryId: 3, isActive: true },
    { name: 'Car News China', rssUrl: 'https://carnewschina.com/feed/', categoryId: 2, isActive: true },
  ]).onConflictDoNothing();

  console.log('Seeding sales data...');
  await db.insert(salesData).values([
    // China
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Qin', month: 12, year: 2024, salesCount: 42000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Qin', month: 1, year: 2025, salesCount: 38000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Qin', month: 2, year: 2025, salesCount: 35000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Qin', month: 3, year: 2025, salesCount: 40000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Qin', month: 4, year: 2025, salesCount: 43000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Qin', month: 5, year: 2025, salesCount: 45000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Song', month: 12, year: 2024, salesCount: 55000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Song', month: 1, year: 2025, salesCount: 48000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Song', month: 2, year: 2025, salesCount: 46000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Song', month: 3, year: 2025, salesCount: 51000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Song', month: 4, year: 2025, salesCount: 53000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Song', month: 5, year: 2025, salesCount: 56000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Seal', month: 12, year: 2024, salesCount: 18000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Seal', month: 1, year: 2025, salesCount: 16000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Seal', month: 2, year: 2025, salesCount: 15000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Seal', month: 3, year: 2025, salesCount: 17000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Seal', month: 4, year: 2025, salesCount: 19000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Seal', month: 5, year: 2025, salesCount: 21000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Han', month: 12, year: 2024, salesCount: 22000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Han', month: 1, year: 2025, salesCount: 20000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Han', month: 2, year: 2025, salesCount: 18000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Han', month: 3, year: 2025, salesCount: 21000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Han', month: 4, year: 2025, salesCount: 23000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Han', month: 5, year: 2025, salesCount: 25000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Dolphin', month: 12, year: 2024, salesCount: 32000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Dolphin', month: 1, year: 2025, salesCount: 28000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Dolphin', month: 2, year: 2025, salesCount: 26000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Dolphin', month: 3, year: 2025, salesCount: 30000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Dolphin', month: 4, year: 2025, salesCount: 33000, dataSource: 'CPCA' },
    { region: 'Asia', country: 'China', vehicleModel: 'BYD Dolphin', month: 5, year: 2025, salesCount: 35000, dataSource: 'CPCA' },
    // Thailand
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Atto 3', month: 12, year: 2024, salesCount: 2800, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Atto 3', month: 1, year: 2025, salesCount: 2200, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Atto 3', month: 2, year: 2025, salesCount: 2500, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Atto 3', month: 3, year: 2025, salesCount: 2900, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Atto 3', month: 4, year: 2025, salesCount: 3100, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Atto 3', month: 5, year: 2025, salesCount: 3200, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Seal', month: 12, year: 2024, salesCount: 1200, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Seal', month: 1, year: 2025, salesCount: 1100, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Seal', month: 2, year: 2025, salesCount: 1300, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Seal', month: 3, year: 2025, salesCount: 1500, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Seal', month: 4, year: 2025, salesCount: 1600, dataSource: 'AutoThai' },
    { region: 'Asia', country: 'Thailand', vehicleModel: 'BYD Seal', month: 5, year: 2025, salesCount: 1700, dataSource: 'AutoThai' },
    // Brazil
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Song', month: 12, year: 2024, salesCount: 1800, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Song', month: 1, year: 2025, salesCount: 1600, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Song', month: 2, year: 2025, salesCount: 1700, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Song', month: 3, year: 2025, salesCount: 1900, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Song', month: 4, year: 2025, salesCount: 2000, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Song', month: 5, year: 2025, salesCount: 2100, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Dolphin', month: 12, year: 2024, salesCount: 900, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Dolphin', month: 1, year: 2025, salesCount: 850, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Dolphin', month: 2, year: 2025, salesCount: 920, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Dolphin', month: 3, year: 2025, salesCount: 980, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Dolphin', month: 4, year: 2025, salesCount: 1050, dataSource: 'Fenabrave' },
    { region: 'South America', country: 'Brazil', vehicleModel: 'BYD Dolphin', month: 5, year: 2025, salesCount: 1100, dataSource: 'Fenabrave' },
    // Germany
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Seal', month: 12, year: 2024, salesCount: 1500, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Seal', month: 1, year: 2025, salesCount: 1300, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Seal', month: 2, year: 2025, salesCount: 1400, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Seal', month: 3, year: 2025, salesCount: 1600, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Seal', month: 4, year: 2025, salesCount: 1700, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Seal', month: 5, year: 2025, salesCount: 1800, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Atto 3', month: 12, year: 2024, salesCount: 800, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Atto 3', month: 1, year: 2025, salesCount: 700, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Atto 3', month: 2, year: 2025, salesCount: 750, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Atto 3', month: 3, year: 2025, salesCount: 820, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Atto 3', month: 4, year: 2025, salesCount: 880, dataSource: 'KBA' },
    { region: 'Europe', country: 'Germany', vehicleModel: 'BYD Atto 3', month: 5, year: 2025, salesCount: 920, dataSource: 'KBA' },
    // Norway
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Tang', month: 12, year: 2024, salesCount: 850, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Tang', month: 1, year: 2025, salesCount: 780, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Tang', month: 2, year: 2025, salesCount: 820, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Tang', month: 3, year: 2025, salesCount: 900, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Tang', month: 4, year: 2025, salesCount: 930, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Tang', month: 5, year: 2025, salesCount: 950, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Seal', month: 12, year: 2024, salesCount: 600, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Seal', month: 1, year: 2025, salesCount: 550, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Seal', month: 2, year: 2025, salesCount: 580, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Seal', month: 3, year: 2025, salesCount: 620, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Seal', month: 4, year: 2025, salesCount: 650, dataSource: 'OFV' },
    { region: 'Europe', country: 'Norway', vehicleModel: 'BYD Seal', month: 5, year: 2025, salesCount: 680, dataSource: 'OFV' },
    // Australia
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Atto 3', month: 12, year: 2024, salesCount: 2100, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Atto 3', month: 1, year: 2025, salesCount: 1900, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Atto 3', month: 2, year: 2025, salesCount: 2000, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Atto 3', month: 3, year: 2025, salesCount: 2200, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Atto 3', month: 4, year: 2025, salesCount: 2300, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Atto 3', month: 5, year: 2025, salesCount: 2400, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Seal', month: 12, year: 2024, salesCount: 1100, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Seal', month: 1, year: 2025, salesCount: 1000, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Seal', month: 2, year: 2025, salesCount: 1050, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Seal', month: 3, year: 2025, salesCount: 1150, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Seal', month: 4, year: 2025, salesCount: 1200, dataSource: 'VFACTS' },
    { region: 'Oceania', country: 'Australia', vehicleModel: 'BYD Seal', month: 5, year: 2025, salesCount: 1250, dataSource: 'VFACTS' },
    // Israel
    { region: 'Asia', country: 'Israel', vehicleModel: 'BYD Atto 3', month: 12, year: 2024, salesCount: 1500, dataSource: 'ICDA' },
    { region: 'Asia', country: 'Israel', vehicleModel: 'BYD Atto 3', month: 1, year: 2025, salesCount: 1300, dataSource: 'ICDA' },
    { region: 'Asia', country: 'Israel', vehicleModel: 'BYD Atto 3', month: 2, year: 2025, salesCount: 1400, dataSource: 'ICDA' },
    { region: 'Asia', country: 'Israel', vehicleModel: 'BYD Atto 3', month: 3, year: 2025, salesCount: 1600, dataSource: 'ICDA' },
    { region: 'Asia', country: 'Israel', vehicleModel: 'BYD Atto 3', month: 4, year: 2025, salesCount: 1700, dataSource: 'ICDA' },
    { region: 'Asia', country: 'Israel', vehicleModel: 'BYD Atto 3', month: 5, year: 2025, salesCount: 1800, dataSource: 'ICDA' },
  ]).onConflictDoNothing();

  console.log('Seeding charging stations...');
  await db.insert(chargingStations).values([
    { country: 'China', city: 'Beijing', stationCount: 2500, targetCount: 3000, status: 'active' },
    { country: 'China', city: 'Shanghai', stationCount: 2200, targetCount: 2800, status: 'active' },
    { country: 'China', city: 'Shenzhen', stationCount: 1800, targetCount: 2200, status: 'active' },
    { country: 'Thailand', city: 'Bangkok', stationCount: 150, targetCount: 300, status: 'expanding' },
    { country: 'Thailand', city: 'Chiang Mai', stationCount: 35, targetCount: 80, status: 'expanding' },
    { country: 'Germany', city: 'Berlin', stationCount: 80, targetCount: 200, status: 'expanding' },
    { country: 'Germany', city: 'Munich', stationCount: 55, targetCount: 150, status: 'expanding' },
    { country: 'Germany', city: 'Frankfurt', stationCount: 40, targetCount: 120, status: 'expanding' },
    { country: 'Norway', city: 'Oslo', stationCount: 60, targetCount: 120, status: 'expanding' },
    { country: 'Norway', city: 'Bergen', stationCount: 25, targetCount: 60, status: 'expanding' },
    { country: 'Brazil', city: 'São Paulo', stationCount: 45, targetCount: 150, status: 'expanding' },
    { country: 'Brazil', city: 'Rio de Janeiro', stationCount: 20, targetCount: 80, status: 'expanding' },
    { country: 'Australia', city: 'Sydney', stationCount: 70, targetCount: 150, status: 'expanding' },
    { country: 'Australia', city: 'Melbourne', stationCount: 55, targetCount: 130, status: 'expanding' },
    { country: 'Australia', city: 'Brisbane', stationCount: 30, targetCount: 80, status: 'expanding' },
    { country: 'Israel', city: 'Tel Aviv', stationCount: 40, targetCount: 100, status: 'expanding' },
    { country: 'Japan', city: 'Tokyo', stationCount: 30, targetCount: 100, status: 'expanding' },
    { country: 'Japan', city: 'Osaka', stationCount: 15, targetCount: 60, status: 'expanding' },
    { country: 'UK', city: 'London', stationCount: 50, targetCount: 120, status: 'expanding' },
    { country: 'UK', city: 'Manchester', stationCount: 20, targetCount: 60, status: 'expanding' },
  ]).onConflictDoNothing();

  console.log('Seed complete!');
}

seed().catch(console.error);
